/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --env-file=.dev.vars.example --include-runtime=false src/worker-configuration.d.ts` (hash: f8afa16958a2436c4cf235734b5c55c4)
interface __BaseEnv_Env {
	OAUTH_KV: KVNamespace;
	AUTH_STATE_KV: KVNamespace;
	MEDIA_BUCKET: R2Bucket;
	DB: D1Database;
	VOICE_JOBS_QUEUE: Queue;
	AUTH_RATE_LIMITER: RateLimit;
	MCP_RATE_LIMITER: RateLimit;
	WEB_WRITE_RATE_LIMITER: RateLimit;
	IMAGES: ImagesBinding;
	MCP_AUTH_MODE: "twitch";
	TWITCH_BROADCASTER_ID: "67879379";
	TWITCH_BROADCASTER_LOGIN: "kashiwo";
	TWITCH_REDIRECT_URI: "https://saijiyu-kenkyu.2764.moe/oauth/twitch/callback";
	MIN_FOLLOW_DAYS: "30";
	ELIGIBILITY_CACHE_TTL_SECONDS: "1800";
	TWITCH_CLIENT_ID: string;
	TWITCH_CLIENT_SECRET: string;
	VOICEVOX_CONTAINER: DurableObjectNamespace<import("./index").VoicevoxContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "VoicevoxContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MCP_AUTH_MODE" | "TWITCH_BROADCASTER_ID" | "TWITCH_BROADCASTER_LOGIN" | "TWITCH_REDIRECT_URI" | "MIN_FOLLOW_DAYS" | "ELIGIBILITY_CACHE_TTL_SECONDS" | "TWITCH_CLIENT_ID" | "TWITCH_CLIENT_SECRET">> {}
}
